// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFIHFTnnJwm4DneMaTPnrz2WjuU8KlLzQ',
    appId: '1:882705981155:web:25e2cf586069bc94476fd6',
    messagingSenderId: '882705981155',
    projectId: 'felix-resume',
    authDomain: 'felix-resume.firebaseapp.com',
    databaseURL: 'https://felix-resume-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'felix-resume.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP8jenYXwtFEo_VsBPd6VEqPpCLyi61L4',
    appId: '1:882705981155:android:45c36b3ca4bb3a96476fd6',
    messagingSenderId: '882705981155',
    projectId: 'felix-resume',
    databaseURL: 'https://felix-resume-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'felix-resume.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsNGbSmKXLfF6wuM5kw5NkD01E0b1jJ1Y',
    appId: '1:882705981155:ios:64846c4114c9d190476fd6',
    messagingSenderId: '882705981155',
    projectId: 'felix-resume',
    databaseURL: 'https://felix-resume-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'felix-resume.appspot.com',
    iosClientId: '882705981155-jan3jaddklq3g3gp54aatjq742p6g5c2.apps.googleusercontent.com',
    iosBundleId: 'cv.cv',
  );
}
